### ISSUE TITLE
BS > Button

### ISSUE THREAD

**Issue by RachidBray** [AyeCode/blockstrap-page-builder-blocks#14]
Escaping single quotes from shortcode attributes

The content is written by the user and therefore can potentially include single quotes **(')**. Problem being, with ' single quotes it outputs **'&apos; '** instead of the character **(')**

Step-by-step reproduction instructions
- Add a new **BS > Button** or **BS > IconBox block**
- In Link Text field copy/paste this string: **Let's go**

Expected Output
- Let's

Current Output (Edito only)
- let&apos;s

Current Output (Front End)
- It displays the placeholder text

NB: this is a global issue (Same behaviour with BS > Icon Box, BS > Nav Item

**Comment by Stiofan** [comment]
Fixed in Super Duper (not pushed yet)
