### ISSUE TITLE
BS > Button outline

### ISSUE THREAD

**Issue by RachidBray** [AyeCode/blockstrap-page-builder-blocks#18]
We need Outline buttons: https://getbootstrap.com/docs/4.0/components/buttons/#outline-buttons
![image](https://user-images.githubusercontent.com/3275173/199495297-c09155e1-99d5-4f33-81a3-1027f8638bfc.png)

**Comment by Stiofan** [comment]
The outlne style is set from the color, it was missing, I have added it.
