### ISSUE TITLE
BS > Tabs

### ISSUE THREAD

**Issue by RachidBray** [AyeCode/blockstrap-page-builder-blocks#23]
- We need option to enable disable border
- We need to add alignement sd_get_flex_justify_content_input_group() to Tabs Head  (see screenshot)
- We need border radius size controller for pills

![image](https://user-images.githubusercontent.com/3275173/200856509-99e39e83-2633-4b01-9459-49c163ecefd1.png)

**Comment by Stiofan** [comment]
done, though i just remove border on pills style instead of giving a setting
