### ISSUE TITLE
BS > Nav

### ISSUE THREAD

**Issue by RachidBray** [AyeCode/blockstrap-page-builder-blocks#28]
We need a way to set vertical spacing between nav item (See screenshot)
![image](https://user-images.githubusercontent.com/3275173/203571237-8de25f7b-8d10-40f2-a384-576a7a81eb32.png)

**Comment by Stiofan** [comment]
this has to be set on individual nav items, I'm not sure if I had added this when u opened this but that is now possible, so hopefully this is resolved.
