### ISSUE TITLE
Add more spacing sizes

### ISSUE THREAD

**Issue by RachidBray** [AyeCode/blockstrap-page-builder-blocks#3]
To have more control we need to add more sizes.
Example (see screenshot), this is the max spacing i can add.

![image](https://user-images.githubusercontent.com/3275173/197504811-90c51ecd-c8d4-4ef0-9476-513590def719.png)

Obviously we can add more spaces (by also adding spaces to inner container) but it's not intuitive.

We can add more entries to the $spacers Sass map variable.
```
$spacers: map-merge(
  (
    0: 0,
    1: ($spacer * .25),
    2: ($spacer * .5),
    3: $spacer,
    4: ($spacer * 1.5),
    5: ($spacer * 3)
  ),
  $spacers
);
```

**Comment by Stiofan** [comment]
i don't want to change the 1-5 values as these are already in use for many users.
