### ISSUE TITLE
The magnifying glass on hover should be optional. 

### ISSUE THREAD

**Issue by pol76** [AyeCode/blockstrap-page-builder-blocks#34]
Or not there at all.

It looks like an old UI/UX

**Comment by Stiofan** [comment]
What should the options be to make it more modern?

**Comment by pol76** [comment]
Nothing apart from the cursor change as with links. Users kniw that clicking on pictures of a gallery it will open them up. Check Airbnb listings.

**Comment by Stiofan** [comment]
Will be in next release
