### ISSUE TITLE
BS > Icon Box

### ISSUE THREAD

**Issue by RachidBray** [AyeCode/blockstrap-page-builder-blocks#35]
- Even it there is no description/title the default one appear. (Check screenshot)
- There is no way to align icons and title in on line
![image](https://user-images.githubusercontent.com/3275173/207029950-066cd8a0-a541-4aff-9e50-2cb883743201.png)

**Comment by RachidBray** [comment]
We can achieve this if we have the Display controller (Flex...) like other widgets

**Comment by Stiofan** [comment]
Fixed, will be in next push
