### ISSUE TITLE
Backend not wyswyg

### ISSUE THREAD

**Issue by pol76** [AyeCode/blockstrap-page-builder-blocks#51]
I tried to use 2 columns in the docs and got what I expected in the frontend, while in the backend, styles are not applied.
 
### Frontend (correct)
![image](https://user-images.githubusercontent.com/25163253/230681356-d8aee4ac-a515-46dc-9a95-124c0feac789.png)

### Backend (wrong)
![image](https://user-images.githubusercontent.com/25163253/230681305-55f8d1bd-2fc4-47fd-9e81-08d5bc32ddde.png)

We must have the front and back look as similar as possible.

Thanks

**Comment by Stiofan** [comment]
Was this for a single post or the actual template?

**Comment by pol76** [comment]
the example above is from a single docs page
