### ISSUE TITLE
<?php tag in CODE or PREFORMTTED blocks breaks html output of posts and pages

### ISSUE THREAD

**Issue by pol76** [AyeCode/blockstrap-page-builder-blocks#56]
The <?php tag in CODE or PREFORMATTED blocks, breaks html output of posts and pages

See: https://wp-rankings.com/wp-admin/post.php?post=56521&action=edit

The problem disappears when the plugin is deactivated.

Please fix ASAP

**Comment by RachidBray** [comment]
The link above points to and admin dashboard.

**Comment by RachidBray** [comment]
Where can we view this?

**Comment by pol76** [comment]
Any test site with blockstrap theme and plugin installed. 

Just add a Code or Preformatted block and add this:

`<?PHP
/*
Plugin Name: My Custom Plugin
Plugin URI: https://example.com/my-custom-plugin
Description: A brief description of your custom plugin.
Version: 1.0.0
Author: Your Name
Author URI: https://example.com
License: GPLv2 or later
Text Domain: my-custom-plugin
*/
`
It will break the rest of the page.

**Comment by pol76** [comment]
If you remove the <?php tag it works. If you disable the Blockstrap Plugin even if you don't remove the <?PHP tag, the page is rendered correctly in the front end.

**Comment by RachidBray** [comment]
Hmmm, it works as it should on my side:
![image](https://github.com/AyeCode/blockstrap-page-builder-blocks/assets/3275173/4f709d70-5ead-46ff-bb2a-9168c6a29787)
I'll investigate further...

**Comment by pol76** [comment]
This is a test on the wpblockstrap.com site:

Backend with preformatted block
![image](https://github.com/AyeCode/blockstrap-page-builder-blocks/assets/25163253/38415a7d-e690-43a1-9fd6-b99c162c1638)

Result in front end
![image](https://github.com/AyeCode/blockstrap-page-builder-blocks/assets/25163253/72405b78-c5b6-4293-8c94-9abc192c9e5e)

Backend with code block
![image](https://github.com/AyeCode/blockstrap-page-builder-blocks/assets/25163253/38415a7d-e690-43a1-9fd6-b99c162c1638)

Result in front end
![image](https://github.com/AyeCode/blockstrap-page-builder-blocks/assets/25163253/bcf42cc5-b778-4c34-a904-a732c8f08df5)

I get the same result on wp-rankings.com

**Comment by pol76** [comment]
thanks for testing further

**Comment by Stiofan** [comment]
found the issue and fixed. (will be in next release today)
