### ISSUE TITLE
Icon Box Block Style settings 

### ISSUE THREAD

**Issue by pol76** [AyeCode/blockstrap-page-builder-blocks#57]
Title style, icon style, and description style all have the last option without a description that I'm not exactly sure what it is.

![icon-box-style-options](https://github.com/AyeCode/blockstrap-page-builder-blocks/assets/25163253/c3953e94-b5c7-44be-ae44-70b8a67354a3)

**Comment by RachidBray** [comment]
It's a spacing controller
I think adding a label would make it easier to use.

**Comment by Stiofan** [comment]
Its padding for the bottom, i have replaced it with a text label
