### ISSUE TITLE
unable to activate plugin for fatal error

### ISSUE THREAD

**Issue by pol76** [AyeCode/blockstrap-page-builder-blocks#67]
Plugin could not be activated because it triggered a fatal error.

https://wordpress-492495-4290590.cloudwaysapps.com/wp-admin/index.php

**Comment by kprajapatii** [comment]
Fixed in [v0.1.10](https://github.com/AyeCode/blockstrap-page-builder-blocks/commit/90b203f66a93d9d1319768493b2d77c9670735da)
