### ISSUE TITLE
Site editor is freezing, unresponsive, and the visibility conditions are not working.

### ISSUE THREAD

**Issue by fucknyan** [AyeCode/blockstrap-page-builder-blocks#83]
Hello, I am experiencing issues while editing my website with the site editor. I just updated the BlockStrap theme to the latest version (everything was working fine before the update).

**The issues encountered:**

1. The site editor lags on every page that uses BS blocks, and often freezes, becoming unresponsive when scrolling, sometimes causing the browser tab to freeze.
2. The visibility conditions feature is not working (it was working fine before the update).

**Steps to reproduce the error:**

1. Go to the site editor of any page that uses BS blocks, in list view, select a series (or two) of BS blocks by pressing shift, and then the tab will freeze and cannot be reloaded, forcing the tab to be closed (I have tried this on Chrome, Edge, and Firefox). Sometimes, just hovering and scrolling in the site editor makes everything unresponsive (I think this depends on whether the page uses many blocks).
2. Simple conditions like hiding block for logged-out users or hiding block for logged-in users are not working.

I went to the staging site, deactivated all plugins except BlockStrap Page Builder Blocks, and the issue persisted. Then, I deactivated BlockStrap and enabled everything else, and the site editor had no issues, so I believe the problem lies with BlockStrap.

This picture was taken after I selected two BS>container fluid with shift, and it froze the entire site editor (not the browser).

![image](https://github.com/user-attachments/assets/22ec7ac0-b177-40c1-9cac-081ba42c0dfb)

If you need information on how to reproduce the error, I will record my screen.

Thanks in advance!

**Comment by fucknyan** [comment]
I checked today issue only persists while in full site editor. Here's the log from my site:

Message
PHP Warning:  Undefined array key "description" in /wordpress/plugins/full-site-editing/4.29247/starter-page-templates/class-starter-page-templates.php on line 372
Timestamp
2024-07-30T20:35:39.000Z
Kind
plugins
Name
full-site-editing
File
/wordpress/plugins/full-site-editing/4.29247/starter-page-templates/class-starter-page-templates.php
Line
372

**Comment by pol76** [comment]
@kprajapatii can you please have a look?

**Comment by kprajapatii** [comment]
Hello @fucknyan,

Error you mentioned is coming from the plugin [WordPress.com Editing Toolkit](https://wordpress.org/plugins/full-site-editing/). 

This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress. See https://wordpress.org/plugins/full-site-editing/

Are you still facing issues with BlockStrap that you mentioned in early post?

Regards,
Kiran

**Comment by fucknyan** [comment]
HI @kprajapatii,
Thank you for getting back to me. 

The log error I mentioned no longer exists. And yes I am still facing the same issues with BlockStrap I mentioned earlier, both full site editor & page editor, especially when it comes to pages that I use many layers or BS blocks. Deactivating **WordPress.com Editing Toolkit** doesn't seem to affect anything. Other pages that I use just a few BS blocks work perfectly fine while editing.

- Here is my website: https://letsspeakvietnamese.com/ if you don't mind checking it
+ 2 pages I have the most issues with are the frontpage and this https://letsspeakvietnamese.com/upcoming-vietnamese-classes/

If you need any more info please let me know

**Comment by fucknyan** [comment]
https://github.com/user-attachments/assets/e05d217f-e36f-460c-bd29-27aafcdfa2be

Here you go, it's a bit long I sped it up 1.5x, please bear with me 😅. I don't think I have these issues with containers that have a lot in them before this post (before WP's update on July)

**Comment by fucknyan** [comment]
I appreciate your help,
I have opened a support request with this email: gumguma2611@gmail.com

**Comment by Stiofan** [comment]
resolved
